name: 'olist_analytics'
version: '1.0.0'
config-version: 2

profile: 'olist_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

models:
  olist_analytics:
    +materialized: view
